language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: 7.0
          env: deps=low
    fast_finish: true

env:
    global:
        - deps=no

before_install:
    - export SYMFONY_PHPUNIT_DIR="$(pwd)/.phpunit"
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI_FILE
    - phpenv config-rm xdebug.ini

install:
    - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then composer remove --dev --no-update symfony/psr-http-message-bridge zendframework/zend-diactoros; fi;
    - if [ "$deps" = "no" ]; then composer install; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
    - ./vendor/bin/simple-phpunit
